tod-org/tod

- CHANGELOG.md
- src/config.rs
> chore: save config rather than deleting and recreating

- .github/workflows/ci.yml
- .gitignore
- CHANGELOG.md
- README.md
- test.sh
> chore: add coverage

- .github/workflows/ci.yml
- test.sh
> chore: make clippy stricter

- CHANGELOG.md
- README.md
- src/config.rs
- src/main.rs
- src/request.rs
- src/request/next_item.rs
> chore: add --complete

- CHANGELOG.md
- src/request/next_item.rs
> chore: display today instead of data when today

- CHANGELOG.md
- README.md
- src/items.rs
- src/projects.rs
- src/request.rs
- src/test.rs
- src/time.rs
> add overdue_items

- README.md
Hi. I came across this repository as I'm loving todoist and also learning Rust. They're minor ones, but this PR is trying to fix the followings. Thanks.
- Fix typo (`possble` -> `possible`).
- Update notes about project name spaces.
- I think the command works well, as long as the argument is properly quoted on the shell (`tod -p "Some Project"`).
- Unit test executions succeeded locally.
```shell
$ cargo test
Finished test [unoptimized + debuginfo] target(s) in 0.10s
Running unittests (target/debug/deps/tod-7400083d4e1a899d)
running 28 tests
test config::tests::new_should_generate_config ... ok
...
test request::tests::should_prioritize_an_item ... ok
test result: ok. 28 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s
```
> Fix typo and update notes about project name spaces

- src/projects.rs
Temporary fix for test errors due to daylight savings causing test expection to fail. Proper fix coming later!﻿
> Temp fix daylight savings test error

- src/config.rs
I changed `generate_path` to use `config_dir` instead of `home_dir`, moved the contents of the old `generate_path` to a new function called `check_legacy_path` to check if a config already exists in the old location and move it.
#128
> Changed default config location

- CHANGELOG.md
- src/config.rs
- src/main.rs
- src/projects.rs
- src/request.rs
> Add better messaging in terminal

- CHANGELOG.md
- src/config.rs
- src/main.rs
- src/projects.rs
attempt to address https://github.com/alanvardy/tod/issues/329
> add ability to skip task when processing the project

- CHANGELOG.md
- codecov.yml
- manual_test.sh
- src/config.rs
- src/items.rs
- src/main.rs
- src/projects.rs
- src/request.rs
Moving branch over here from your repo @titoOdUA so I can add commits too
Original PR: https://github.com/alanvardy/tod/pull/347
> add priority to the creating process of the task

- src/projects.rs
> Add skip to project empty

- CHANGELOG.md
- src/items.rs
- src/items/priority.rs
- src/main.rs
- src/projects.rs
- src/test.rs
- src/todoist.rs
> Improve priorities

- CHANGELOG.md
- README.md
- src/cargo.rs
- src/config.rs
- src/main.rs
> Version check

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/color.rs
- src/config.rs
- src/items.rs
- src/main.rs
- src/projects.rs
- src/test.rs
> Show item count in project list

- src/main.rs
- src/projects.rs
> Add task count to task next

- CHANGELOG.md
- src/items.rs
- src/main.rs
- src/projects.rs
> Add overdue to schedule

- CHANGELOG.md
- src/main.rs
- src/projects.rs
- src/time.rs
- src/todoist.rs
> Add due flag to task create

- CHANGELOG.md
- src/config.rs
- src/main.rs
- src/projects.rs
> Tod project rename

- CHANGELOG.md
- src/items.rs
- src/projects.rs
- src/test.rs
> Dont reschedule recurring tasks

- CHANGELOG.md
- src/config.rs
- src/main.rs
- src/projects.rs
> Auto remove projects

- CHANGELOG.md
- src/main.rs
- src/projects.rs
> Add project remove --all

- CHANGELOG.md
- DELETEME
- src/main.rs
- src/projects.rs
- src/test.rs
- src/todoist.rs
- src/todoist/request.rs
> Create task asks for section

- CHANGELOG.md
- DELETEME
- README.md
- src/config.rs
- src/input.rs
- src/projects.rs
- src/test.rs
> Add natural language only

- src/filters.rs
- src/projects.rs
- src/tasks.rs
- src/tasks/priority.rs
> Fix reversed priorities

- CHANGELOG.md
- docs/configuration.md
- docs/usage.md
- src/config.rs
- src/tasks.rs
- src/test.rs
> Customizable scoring

- src/color.rs
- src/debug.rs
- src/main.rs
- src/projects.rs
- src/todoist/request.rs
> Fix rename project

- CHANGELOG.md
- src/projects.rs
- src/todoist.rs
- src/todoist/request.rs
> Add delete option

- CHANGELOG.md
- src/config.rs
> using verbose flag should not overwrite config

- CHANGELOG.md
- src/tasks.rs
- src/test.rs
- src/todoist.rs
> Print task durations

- Cargo.lock
- src/input.rs
> Better date prompt description

- src/main.rs
Hi,
First of all, thank you for building such a great program! I like it so much! ❤️
As I mentioned in issue #949, the shell completions command should not rely on the user's config or a valid TOKEN, as this creates unnecessary complications in scenarios like packaging the software for distribution. Decoupling the shell completions command simplifies this process and aligns with best practices.
This PR refactors the handling of shell completions to remove the dependency on the configuration.
The current implementation may not be the best approach, as it handles the shell completions logic outside of the main match block and directly sets the bell flags to false instead of relying on the configuration. While this achieves the desired decoupling, I would greatly appreciate it if you could …
> Refactor(shell): Decouple shell completions from config

- .rusty-hook.toml
- Cargo.lock
- Cargo.toml
- src/cargo.rs
- src/config.rs
- src/filters.rs
- src/input.rs
- src/list.rs
- src/main.rs
- src/projects.rs
- src/tasks.rs
- src/tasks/format.rs
- src/test.rs
- src/time.rs
- src/todoist.rs
- src/todoist/request.rs
Updating for Rust 2024 (see https://github.com/alanvardy/tod/issues/1014)
> 2024 edition

- docs/configuration.md
- docs/installation.md
- docs/usage.md
Minor MD Linter formatting cleanup - no code changes.
> Markdown Lint Cleanup

- src/comments.rs
- src/config.rs
Add handling of ImageAttachment format
Resolves #1132
> Add imageAttachment and exit upon invalid config

- CHANGELOG.md
- docs/configuration.md
- docs/usage.md
Documentation updates to include latest changes
> Doc updates

- .github/dependabot.yml
Update Dependabot to also check Github actions
> Update dependabot.yml to include Github Actions

- .github/workflows/pr_check.yml
simplify naming of file and format cleanup
> ci: update pr_check.yml

- scripts/auto_release.sh
creates auto_release.sh for release via release-please
> chore: create auto_release

- .github/pull_request_template.md
creates pull_request_template.md
> docs: pr template

- .github/workflows/release_linux.yml
- .github/workflows/release_macos.yml
- .github/workflows/release_windows.yml
rename releases to setup for homebrew/CI automation
> ci: update release workflow files

- README.md
> Trying a different way to format the codecov badge
> Please confirm all items below before requesting a review:
> Link any related issues here using `Closes #issue-number`, `Fixes #issue-number`, etc.
> chore: update codecov badge

- bucket/tod.json
add windows scoop json
> Adds windows Scoop Support.
> Link any related issues here using `Closes #issue-number`, `Fixes #issue-number`, etc.
Note: This will provide the basis to resolve #1011 and #1272, however I will need to submit a 2nd PR to update the docs once confirmed that that is done.
This also does not add automatic building/updating of Scoop JSON which will be the next step.
> chore: add scoop json

- .github/workflows/release_windows.yml
- README.md
- docs/installation.md
Updates scoop for automatic generation and updates readme to include scoop
Closes #1272
> chore: (scoop) build automate

- CHANGELOG.md
> Updates the changelog.md format to be consistent with release-please and remove the section that was still labelled as unreleased (even though it was released) and move those into where they should be.
> Link any related issues here using `Closes #issue-number`, `Fixes #issue-number`, etc.
> chore: changelog cleanup

- src/shell.rs
fix command test for mac/windows
Fixes #1378
> Fixes command output test to be compatible with both platforms.
> test: split shell win/mac test

- .github/workflows/rust-clippy.yml
Adds rust clippy monitoring to CI
> ci: add rust-clippy

- .github/workflows/release_please.yml
testing with app_id to fox error.
> ci: testing with app_id

- rust-toolchain.toml
- src/config.rs
- src/shell.rs
formatting and fixes for 1.89
> Briefly describe what this PR does and what it changes.
Fixes #1438
> chore: rust 1.89 fixes

- .github/workflows/release_linux.yml
- .github/workflows/release_macos.yml
- .github/workflows/release_please.yml
- .github/workflows/release_windows.yml
adds repo parameter to tokens
Fixes #1447
> chore: add repo to token

- .commitlint.config.mjs
- .github/dependabot.yml
> chore: commitlint & dependabot fixes

- .github/workflows/gitleaks.yml
Fixes gitleaks tow ork on dependabot
> ci: fix gitleaks to work on dependabot

- .github/copilot-instructions.md
- .github/workflows/ci-secure.yml
- .github/workflows/gitleaks.yml
- .github/workflows/gitleaks/gitleaks.toml
- docs/development.md
> ci: add Gitleaks configuration file
